name: mobile_desa_kumantan
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # <-- Saya ubah ini, lihat penjelasan di bawah

dependencies:
  flutter:
    sdk: flutter
    
  
  carousel_slider: ^5.1.1

  # Untuk UI Cantik
  getwidget: ^6.0.0

  # Font google
  google_fonts: ^6.2.1
  
  # Untuk request API
  http: ^1.2.1

  # Untuk memilih file dari HP
  file_picker: ^8.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg