name: mobile_desa_kumantan
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # PERBAIKAN: Menggunakan versi yang stabil dan kompatibel
  getwidget: ^6.0.0
  carousel_slider: ^5.1.1

  # Dependensi lain
  google_fonts: ^6.2.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  file_picker: ^10.2.0
  dio: ^5.8.0+1
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  firebase_messaging: ^15.2.7
  firebase_core: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

env  assets:
  - .
